### ISSUE TITLE
Class Naming

### ISSUE THREAD

**Issue by moondemon68** [rayhankinan/Tubes02-OOP#1]
`Temporary` is not a really good class name as it does not tell the reader what the word "temporary" refers to. A possible better name to use could be "TemporarySpell".

This issue is only a suggestion. You may argue with it (not all the suggestions are true), challenge it, or come up with another idea yourself.

**Comment by rayhankinan** [comment]
Udah aku ganti ya kak, dari Temporary.java jadi Inactiveable mungkin ya kak?

**Comment by moondemon68** [comment]
Hmm, dia tetap "mengaktifkan" kan ya, tapi gak permanen?

**Comment by rayhankinan** [comment]
Iya kak, aku jadi ubah namanya mungkin menjadi Applicable untuk yang permanent dan Revertable untuk yang temporary. Apakah lebih baik kak untuk konvensi penamaannya?

**Comment by moondemon68** [comment]
Kalau jadi Irreversible dan Reversible gimana? Biar mempermudah aja ketika mau membedakan.
