### ISSUE TITLE
Potential Bugs

### ISSUE THREAD

**Issue by moondemon68** [rayhankinan/Tubes02-OOP#2]
I have found several potential bugs, hope this can help:

- https://github.dev/rayhankinan/Tubes02-OOP/blob/9d2d5beb912dd7079e3f965e0989979d75dfef0c/src/main/java/com/aetherwars/model/card/character/Character.java#L88-L92
Make sure that all active potion spells values are also swapped. I think right now, only the character's base attack and health values are swapped.
- https://github.dev/rayhankinan/Tubes02-OOP/blob/9d2d5beb912dd7079e3f965e0989979d75dfef0c/src/main/java/com/aetherwars/model/card/character/SummonedCharacter.java#L129-L137
Don't forget that the maximum level in this game is 10, not 9.

This issue is only a suggestion. You may argue with it (not all the suggestions are true), challenge it, or come up with another idea yourself.

**Comment by rayhankinan** [comment]
Untuk yang maximum level sudah aku implementasikan solusinya kak, tetapi untuk yang swap spell tersebut, aku masih sedikit-sedikit kebingungan mengenai nilai apa sajakah yang harus diswap. Untuk saat ini, aku baru melakukan swapping antara temporary attributes yang disebabkan oleh potion dengan current attributes character saat itu. Untuk attack up dan health up tersebut apakah tidak usah dilakukan swapping kak?

**Comment by moondemon68** [comment]
Betul, yang penting yang terlihat di karakter (nilai current health dan attack, termasuk didalamnya base health/atk dan potion buffs) di swap. Atkup dan healthup adalah bagian dari atribut kartu (bukan karakternya), jadi gak perlu diswap.
